<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYp2gGP8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYp2gGP8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYp2gGP8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYp2gGP8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYp2gGP8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yp2gGP8',
    'container.build_id' => 'f94613ed',
    'container.build_time' => 1784233038,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYp2gGP8');
