<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEo5OkHJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEo5OkHJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEo5OkHJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEo5OkHJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEo5OkHJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Eo5OkHJ',
    'container.build_id' => 'd6806e67',
    'container.build_time' => 1784279212,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEo5OkHJ');
