<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_reader' => [[], ['_controller' => 'App\\Controller\\ReaderController::index'], [], [['text', '/reader']], [], [], []],
    'app_reader_get' => [['id'], ['_controller' => 'App\\Controller\\ReaderController::getReader'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reader']], [], [], []],
    'App\Controller\ReaderController::index' => [[], ['_controller' => 'App\\Controller\\ReaderController::index'], [], [['text', '/reader']], [], [], []],
    'App\Controller\ReaderController::getReader' => [['id'], ['_controller' => 'App\\Controller\\ReaderController::getReader'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reader']], [], [], []],
];
