<?php

namespace Container8sEEwUr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReaderMapperService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Mapper\ReaderMapper' shared autowired service.
     *
     * @return \App\Mapper\ReaderMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Mapper/ReaderMapper.php';

        return $container->privates['App\\Mapper\\ReaderMapper'] = new \App\Mapper\ReaderMapper();
    }
}
