<?php

namespace ContainerMNhnI9U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReaderServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\ReaderService' shared autowired service.
     *
     * @return \App\Service\ReaderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ReaderService.php';

        return $container->privates['App\\Service\\ReaderService'] = new \App\Service\ReaderService(($container->privates['App\\Repository\\ReaderRepository'] ?? $container->load('getReaderRepositoryService')));
    }
}
