name: CI
on:
    pull_request:
        branches:
            - "dev"
    push:
        branches:
            - "**"

jobs:
    build-test-symfony:
        runs-on: ubuntu-latest

        steps:
            - name: Install checkout
              uses: actions/checkout@v7

            - name: Create .env file for CI
              run: |
                echo "POSTGRES_USER=echo_user" >> .env
                echo "POSTGRES_PASSWORD=echo_password" >> .env
                echo "POSTGRES_DB=echo_db" >> .env
                echo "DEFAULT_URI=http://localhost" >> .env
                echo "DATABASE_URL=postgresql://echo_user:echo_password@postgres_sy:5432/echo_db?serverVersion=18&charset=utf8" >> .env
                
                echo "KEYCLOAK_ADMIN=admin" >> .env
                echo "KEYCLOAK_ADMIN_PASSWORD=admin_secret_password" >> .env
                echo "POSTGRES_KEYCLOAK_USER=keycloak_user" >> .env
                echo "POSTGRES_KEYCLOAK_PASSWORD=keycloak_password" >> .env
                echo "POSTGRES_KEYCLOAK_DB=keycloak_db" >> .env
                echo "KEYCLOAK_PORT=8081" >> .env

                echo "KEYCLOAK_URL=http://keycloak_service:8080" >> .env
                echo "KEYCLOAK_REALM=myrealm" >> .env
                echo "KEYCLOAK_CLIENT_ID=symfony_client" >> .env
                echo "KEYCLOAK_CLIENT_SECRET=secret_test_ci" >> .env

            - name: Build Docker Services
              run: docker compose build

            - name: Start Docker Services
              run: docker compose up -d

            - name: Wait for Keycloak health
              run: |
                echo "Waiting for Keycloak to start..."
                until [ "$(docker inspect --format='{{json .State.Health.Status}}' keycloak_service 2>/dev/null)" = '"healthy"' ] || curl -s http://localhost:8081/health/ready > /dev/null; do
                  sleep 3
                done
                echo "Keycloak is ready !"

            - name: Install dependencies
              run: |
                  docker compose exec -T php_composer composer install \
                  --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
                  
            - name: Run tests
              run: docker compose exec -T php_composer vendor/bin/phpunit

            - name: Stop and clean containers
              if: always()
              run: docker compose down -v

    security-trivy-fs:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Run Trivy filesystem scan
          uses: aquasecurity/trivy-action@v0.36.0
          with:
            scan-type: fs
            scan-ref: .
            format: table
            severity: HIGH,CRITICAL

    security-trivy-image:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - run: docker compose build

        - name: Scan image
          uses: aquasecurity/trivy-action@v0.36.0
          with:
            image-ref: php_composer
            severity: CRITICAL,HIGH
            exit-code: 1

        - name: Generate SBOM
          uses: aquasecurity/trivy-action@v0.36.0
          with:
            scan-type: fs
            scan-ref: .
            format: cyclonedx
            output: sbom.json